function inIframe() {
    try {
        return window.self !== window.top;
    } catch (e) {
        return true;
    }
}

var colors = [
    '#490A3D',
    '#BD1550',
    '#E97F02',
    '#F8CA00',
    '#8A9B0F',
    '#69D2E7',
    '#FA6900',
    '#16a085',
    '#27ae60',
    '#2c3e50',
    '#f39c12',
    '#e74c3c',
    '#9b59b6',
    '#FB6964',
    '#342224',
    '#472E32',
    '#77B1A9',
    '#73A857',
    '#FF5733',
    '#2471A3',
    '#D35400',
    '#C0392B',
    '#3498DB',
    '#8E44AD',
    '#E74C3C',
    '#3498DB',
    '#2980B9',
    '#2ECC71',
    '#27AE60',
    '#16A085',
    '#F39C12',
    '#D35400',
    '#3498DB',
    '#E74C3C',
    '#8E44AD',
    '#2E86C1',
    '#85C1E9',
    '#1ABC9C',
    '#D35400',
    '#8E44AD',
    '#3498DB',
    '#F1C40F',
    '#D35400',
    '#3498DB',
    '#2471A3',
    '#8E44AD',
    '#F1C40F',
    '#E74C3C'
];

// Add more colors here...

var quotes = [
    ["You only live once, but if you do it right, once is enough.","Mae West"],
    ["I am so clever that sometimes I don't understand a single word of what I am saying.","Oscar Wilde"],
    ["Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.","Albert Einstein"],
    ["The most beautiful experience we can have is the mysterious. It is the fundamental emotion that stands at the cradle of true art and true science.","Albert Einstein"],
    ["It is our choices, Harry, that show what we truly are, far more than our abilities.","J.K. Rowling, Harry Potter and the Chamber of Secrets"],
    ["All men who have turned out worth anything have had the chief hand in their own education.","Walter Scott"],
    ["Trust yourself. You know more than you think you do.","Benjamin Spock"],
    ["No one can make you feel inferior without your consent.","Eleanor Roosevelt, This is My Story"],
    ["To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.","Ralph Waldo Emerson"],
    ["Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover.","H. Jackson Brown Jr., P.S. I Love You"],
    ["Life is really simple, but we insist on making it complicated.","Confucius"],
    ["Success is not final, failure is not fatal: It is the courage to continue that counts.","Winston Churchill"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best time to plant a tree was 20 years ago. The second best time is now.","Chinese Proverb"],
    ["In three words I can sum up everything I've learned about life: it goes on.","Robert Frost"],
    ["The greatest glory in living lies not in never falling, but in rising every time we fall.","Nelson Mandela"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["The future depends on what you do today.","Mahatma Gandhi"],
    ["Happiness is not something ready made. It comes from your own actions.","Dalai Lama"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["Believe you can and you're halfway there.","Theodore Roosevelt"],
    ["Life is 10% what happens to us and 90% how we react to it.","Charles R. Swindoll"],
    ["The harder I work, the luckier I get.","Samuel Goldwyn"],
    ["If you want to lift yourself up, lift up someone else.","Booker T. Washington"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["Don't let yesterday take up too much of today.","Will Rogers"],
    ["Life is short, and it's up to you to make it sweet.","Sarah Louise Delany"],
    ["The way to get started is to quit talking and begin doing.","Walt Disney"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["You miss 100% of the shots you don't take.","Wayne Gretzky"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["The only thing standing between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["It always seems impossible until it's done.","Nelson Mandela"],
    ["Success is walking from failure to failure with no loss of enthusiasm.","Winston Churchill"],
    ["The secret of getting ahead is getting started.","Mark Twain"],
    ["A person who never made a mistake never tried anything new.","Albert Einstein"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The greatest glory in living lies not in never falling, but in rising every time we fall.","Nelson Mandela"],
    ["Life is 10% what happens to us and 90% how we react to it.","Charles R. Swindoll"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["Life is a journey that must be traveled no matter how bad the roads and accommodations.","Oliver Goldsmith"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["It's not about how hard you hit. It's about how hard you can get hit and keep moving forward.","Rocky Balboa"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.","Steve Jobs"],
    ["Believe you can and you're halfway there.","Theodore Roosevelt"],
    ["To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.","Ralph Waldo Emerson"],
    ["Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.","Albert Schweitzer"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["You are never too old to set another goal or to dream a new dream.","C.S. Lewis"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["You are never too old to set another goal or to dream a new dream.","C.S. Lewis"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["You are never too old to set another goal or to dream a new dream.","C.S. Lewis"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["Life is really simple, but we insist on making it complicated.","Confucius"],
    ["Success is not final, failure is not fatal: It is the courage to continue that counts.","Winston Churchill"],
    ["The best time to plant a tree was 20 years ago. The second best time is now.","Chinese Proverb"],
    ["In three words I can sum up everything I've learned about life: it goes on.","Robert Frost"],
    ["The greatest glory in living lies not in never falling, but in rising every time we fall.","Nelson Mandela"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["The future depends on what you do today.","Mahatma Gandhi"],
    ["Happiness is not something ready made. It comes from your own actions.","Dalai Lama"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["Believe you can and you're halfway there.","Theodore Roosevelt"],
    ["Life is 10% what happens to us and 90% how we react to it.","Charles R. Swindoll"],
    ["The harder I work, the luckier I get.","Samuel Goldwyn"],
    ["If you want to lift yourself up, lift up someone else.","Booker T. Washington"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["Don't let yesterday take up too much of today.","Will Rogers"],
    ["Life is short, and it's up to you to make it sweet.","Sarah Louise Delany"],
    ["The way to get started is to quit talking and begin doing.","Walt Disney"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["You miss 100% of the shots you don't take.","Wayne Gretzky"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["The only thing standing between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["It always seems impossible until it's done.","Nelson Mandela"],
    ["Success is walking from failure to failure with no loss of enthusiasm.","Winston Churchill"],
    ["The secret of getting ahead is getting started.","Mark Twain"],
    ["A person who never made a mistake never tried anything new.","Albert Einstein"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The greatest glory in living lies not in never falling, but in rising every time we fall.","Nelson Mandela"],
    ["Life is 10% what happens to us and 90% how we react to it.","Charles R. Swindoll"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["You are never too old to set another goal or to dream a new dream.","C.S. Lewis"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["You are never too old to set another goal or to dream a new dream.","C.S. Lewis"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["You are never too old to set another goal or to dream a new dream.","C.S. Lewis"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["Life is really simple, but we insist on making it complicated.","Confucius"],
    ["Success is not final, failure is not fatal: It is the courage to continue that counts.","Winston Churchill"],
    ["The best time to plant a tree was 20 years ago. The second best time is now.","Chinese Proverb"],
    ["In three words I can sum up everything I've learned about life: it goes on.","Robert Frost"],
    ["The greatest glory in living lies not in never falling, but in rising every time we fall.","Nelson Mandela"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["The future depends on what you do today.","Mahatma Gandhi"],
    ["Happiness is not something ready made. It comes from your own actions.","Dalai Lama"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["Believe you can and you're halfway there.","Theodore Roosevelt"],
    ["Life is 10% what happens to us and 90% how we react to it.","Charles R. Swindoll"],
    ["The harder I work, the luckier I get.","Samuel Goldwyn"],
    ["If you want to lift yourself up, lift up someone else.","Booker T. Washington"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["Don't let yesterday take up too much of today.","Will Rogers"],
    ["Life is short, and it's up to you to make it sweet.","Sarah Louise Delany"],
    ["The way to get started is to quit talking and begin doing.","Walt Disney"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["You miss 100% of the shots you don't take.","Wayne Gretzky"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["The only thing standing between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["It always seems impossible until it's done.","Nelson Mandela"],
    ["Success is walking from failure to failure with no loss of enthusiasm.","Winston Churchill"],
    ["The secret of getting ahead is getting started.","Mark Twain"],
    ["A person who never made a mistake never tried anything new.","Albert Einstein"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The greatest glory in living lies not in never falling, but in rising every time we fall.","Nelson Mandela"],
    ["Life is 10% what happens to us and 90% how we react to it.","Charles R. Swindoll"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["You are never too old to set another goal or to dream a new dream.","C.S. Lewis"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["You are never too old to set another goal or to dream a new dream.","C.S. Lewis"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["You are never too old to set another goal or to dream a new dream.","C.S. Lewis"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["You are never too old to set another goal or to dream a new dream.","C.S. Lewis"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["You are never too old to set another goal or to dream a new dream.","C.S. Lewis"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["You are never too old to set another goal or to dream a new dream.","C.S. Lewis"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["You are never too old to set another goal or to dream a new dream.","C.S. Lewis"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["You are never too old to set another goal or to dream a new dream.","C.S. Lewis"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["You are never too old to set another goal or to dream a new dream.","C.S. Lewis"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["You are never too old to set another goal or to dream a new dream.","C.S. Lewis"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["You miss 100% of the shots you don't take.","Wayne Gretzky"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["The only thing standing between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["It always seems impossible until it's done.","Nelson Mandela"],
    ["Success is walking from failure to failure with no loss of enthusiasm.","Winston Churchill"],
    ["The secret of getting ahead is getting started.","Mark Twain"],
    ["A person who never made a mistake never tried anything new.","Albert Einstein"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The greatest glory in living lies not in never falling, but in rising every time we fall.","Nelson Mandela"],
    ["Life is 10% what happens to us and 90% how we react to it.","Charles R. Swindoll"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
    ["The best revenge is massive success.","Frank Sinatra"],
    ["The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.","Joel Brown"],
    ["Don't watch the clock; do what it does. Keep going.","Sam Levenson"],
    ["In the middle of every difficulty lies opportunity.","Albert Einstein"],
    ["You are never too old to set another goal or to dream a new dream.","C.S. Lewis"],
    ["Don't count the days, make the days count.","Muhammad Ali"],
    ["The only limit to our realization of tomorrow will be our doubts of today.","Franklin D. Roosevelt"],
    ["It does not matter how slowly you go as long as you do not stop.","Confucius"],
    ["Opportunities don't happen. You create them.","Chris Grosser"],
    ["Life isn't about finding yourself. Life is about creating yourself.","George Bernard Shaw"],
    ["The only true wisdom is in knowing you know nothing.","Socrates"],
    ["The best way to predict the future is to create it.","Peter Drucker"],
    ["Don't let what you cannot do interfere with what you can do.","John Wooden"],
    ["Your time is limited, don't waste it living someone else's life.","Steve Jobs"],
    ["The only person you should try to be better than is the person you were yesterday.","Unknown"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["The only way to do great work is to love what you do.","Steve Jobs"],
	];
		
	// Add more quotes here...
		
var currentQuote = "";
var currentAuthor = "";
var randomquote = "";
var randomcolor = "";

function getQuote() {
	randomquote = Math.floor(Math.random() * quotes.length);
	randomcolor = Math.floor(Math.random() * colors.length);
    currentQuote = quotes[randomquote][0];
    currentAuthor = quotes[randomquote][1];

	$(document).ready(function () {
	    $('html body').animate({
	        backgroundColor: colors[randomcolor],
	        color: colors[randomcolor]
	    }, 500);
			$('blockquote footer').animate({ color: colors[randomcolor] }, 500);	
	    $('blockquote').animate({ borderLeftColor: colors[randomcolor] }, 500);
	    $('#quotetext').animate({ opacity: 0 }, 500, function () {
	        $(this).animate({ opacity: 1 }, 500);
	        $(this).text(currentQuote);
	    });
	    $('#quotesource').animate({ opacity: 0 }, 500, function () {
	        $(this).animate({ opacity: 1 }, 500);
	        $(this).text(currentAuthor);
	    });
    });    
}

function openURL(url) {
    window.open(url, 'Share', 'width=550, height=400, toolbar=0, scrollbars=1 ,location=0 ,statusbar=0,menubar=0, resizable=0');
}

getQuote();

$(document).ready(function () {
    $('#newquote').on('click', getQuote);
});
